#!/bin/sh -e

. /usr/share/initramfs-tools/hook-functions

copy_file() {
	if [ -x ${FILE} ]
	then
		copy_exec ${FILE}
		echo "INFO: ${FILE} copied to initramfs"
	else
		echo "WARNING: ${FILE} does not exist, hook skipped"
	fi
}

FILE="/sbin/fsck"
copy_file
FILE="/sbin/fsck.ext2"
copy_file

