#!/bin/sh

UPDATER="/usr/sbin/update-pepperflashplugin-nonfree"

test -x $UPDATER || exit 0

# exit if not online
nm-online || exit 0

# install checks if the current version is already installed, otherwise upgrades
$UPDATER --install --quiet
