#!/bin/sh

set -e

lb config noauto \
    --apt-indices false \
    --apt-recommends false \
    --architectures amd64 \
    --archive-areas "main contrib non-free" \
    --binary-images iso \
    --distribution jessie \
    --firmware-chroot true \
    --iso-volume "lernstick${SYSTEM_SUFFIX} ${TODAY}" \
    --mirror-binary ${MIRROR_SYSTEM} \
    --mirror-binary-security ${MIRROR_SECURITY_SYSTEM} \
    --mirror-bootstrap ${MIRROR_BUILD} \
    --source ${SOURCE} \
    --verbose
"${@}"
